name: sofizpay_sdk_dart
description: A powerful Dart SDK for SofizPay Payments with real-time transaction monitoring and comprehensive payment management.
version: 1.1.1
homepage: https://github.com/kenandarabeh/sofizpay-sdk-dart
repository: https://github.com/kenandarabeh/sofizpay-sdk-dart
issue_tracker: https://github.com/kenandarabeh/sofizpay-sdk-dart/issues
documentation: https://github.com/kenandarabeh/sofizpay-sdk-dart#readme

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  stellar_flutter_sdk: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

topics:
  - payment
  - sdk
  - dart
  - flutter
  


  
  
# dart pub publish --force